services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - "4031:80"
    depends_on:
      - backend
    restart: always
